server:
  port: 8088
spring:
  application:
    name: drools_springboot
  mail:
    host: smtp.neusoft.com
    port: 587
    username: yang-qs@neusoft.com
    password: Dryqs.2022
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    ssl:
      trust: "*"
management:
  endpoints:
    web:
      exposure:
        include: "*"
